sudo: false
language: go

go:
- "1.x"

matrix:
  include:
  - env: GO111MODULE=on TEST_DB=sqlite3 TEST_DSN=":memory:"
  - env: GO111MODULE=on TEST_DB=postgres TEST_DSN="user=postgres dbname=filedrop_test sslmode=disable"
    services:
    - postgresql
    before_install:
    - psql -c 'create database filedrop_test;' -U postgres

script:
- go test -race -coverprofile=coverage.txt -covermode=atomic -tags $TEST_DB

after_success:
- bash <(curl -s https://codecov.io/bash)
